<Project>
	<ItemGroup Label="Entity Files" Condition="'$(PkgPath)' != ''">
		<Compile Include="$(PkgPath)/UsrBusinessTrip/Schemas/UsrBusinessTrip/UsrBusinessTrip.cs" Condition="Exists('$(PkgPath)/UsrBusinessTrip/Schemas/UsrBusinessTrip/UsrBusinessTrip.cs')" />
		<Compile Include="$(PkgPath)/UsrBusinessTrip/Schemas/UsrBusinessTripStage/UsrBusinessTripStage.cs" Condition="Exists('$(PkgPath)/UsrBusinessTrip/Schemas/UsrBusinessTripStage/UsrBusinessTripStage.cs')" />
		<Compile Include="$(PkgPath)/UsrBusinessTrip/Schemas/UsrTripPurpose/UsrTripPurpose.cs" Condition="Exists('$(PkgPath)/UsrBusinessTrip/Schemas/UsrTripPurpose/UsrTripPurpose.cs')" />
	</ItemGroup>
</Project>